
ARDUINO_DIR = /usr/share/arduino
USER_LIB_PATH = /home/${USER}/Arduino/libraries
BOARD_TAG = mega2560
ARDUINO_PORT = /dev/arduino0
ARDUINO_SKETCHBOOK = /home/${USER}/Arduino/
ARDUINO_LIBS = ros_lib elapsedMillis

include /usr/share/arduino/Arduino.mk
